export {paso1} from "./paso1";
export {paso2} from "./paso2";
export {paso3} from "./paso3";
export {paso4} from "./paso4";
export {paso5} from "./paso5";
export {paso6} from "./paso6";
export {paso4_1} from "./paso4_1";
export {paso7} from "./paso7";
export {renderHome} from "../presentation/renderHome";
